- global.R
- server.R
- ui.R
very basic first files for the global, server and ui
> Set-up for the global, ui and server. Almost empty files. #3

- global.R
- modules/communication_module.R
- modules/select_component.R
- server.R
- ui.R
The communication module uses the selection modules from date and component to filter the data. Also small changes in date and component modules.
The module doen't have visible output, this is added to see that it is working, but should be removed later.
> Issue5 into develop

- global.R
- modules/communication_module.R
- modules/select_component.R
- server.R
- ui.R
This is @Hendricxw 's mystery module. Can't find any related issue (#14 is a PR).
> Branch Issue14

- modules/choose_mun_or_proj.R
fixed bug in municipality dropdown options.
> added Gemeente option to if-statement #83

- global.R
- modules/add_timeseries_plot.R
- modules/communication_module.R
- modules/select_date_range.R
- modules/show_map.R
- server.R
The first steps to connect the database in the tool. The communication module is adapted to get the data from the database. 
The update-button will follow later.
> Issue81 - dbs connection in commodule

- funs/database_fun.R
- funs/download_fun.R
- global.R
- modules/add_metadata_tables.R
- modules/add_timeseries_plot.R
- modules/choose_mun_or_proj.R
- modules/communication_module.R
- modules/download_api_button.R
- modules/select_mun_or_proj.R
- modules/update_data_button.R
- server.R
- ui.R
The functionalities of the download button are implemented, and on the way smalle bugs are fixed in other parts of the tool.
> Issue91 - data download and small fixes

- lang/translation.json
- modules/add_metadata_tables.R
- modules/communication_module.R
- ui.R
Now all the data points are included in the meta-data table, without regarding the selection of stations. #114
> Merge issue114 into develop

- global.R
- modules/add_bar_plot.R
- modules/add_pollutionrose_plot.R
- modules/add_timeseries_plot.R
- modules/add_timevariation_daily_plot.R
- modules/add_timevariation_weekly_plot.R
- modules/communication_module.R
- modules/select_component.R
- server.R
I changed stuff in the global and n the plotting to clean the code and to make something more uniform.
> Issue5 - plotting and validating

- CONTAINER/config-r/Dockerfile
- CONTAINER/config-sys/Dockerfile
- Dockerfile
- dev_environment.R
- funs/database_fun.R
- funs/download_fun.R
- global.R
- scripts/download_demo_database.R
- scripts/init_database.R
- scripts/queue_test.R
Testing branch had some changes due to container deployment, these changes must be merged back into dev branch
> Merge changes from testing

- funs/assign_color_stations.R
- global.R
- modules/add_bar_plot.R
- modules/add_individual_timeseries_plot.R
- modules/add_metadata_param_tables.R
- modules/add_metadata_tables.R
- modules/add_tabpanels.R
- modules/add_timeseries_plot.R
- modules/add_timevariation_daily_plot.R
- modules/add_timevariation_weekly_plot.R
- modules/communication_module.R
- modules/get_data_button.R
- modules/set_groupname_button.R
- modules/show_map.R
- server.R
- ui.R
Group functionality is added to the tool, new modules, and existing data averaging is extended. Also some new visualisations.
Not yet tested with the reference data, I expect it could work.
> Issue123 n

- funs/database_fun.R
- funs/download_fun.R
- funs/queue_fun.R
- global.R
- modules/download_api_button.R
- scripts/create_data_request.R
- scripts/init_database.R
- scripts/queue_manager.R
This PR fixes the download queue (#179)  and also contains some database optimization (#140)
> Merge issue 179 into develop

- modules/add_timeseries_plot.R
- modules/add_timevariation_daily_plot.R
- modules/add_timevariation_weekly_plot.R
> Put legend above plots #issue165

- modules/download_to_pc.R
Issue is fixed, works within a container environment
> Fixed issue #243, download function

- modules/download_to_pc.R
forgot paths in download_to_pc, removed dir paths in zip file, #243
> mergedev into accept

- funs/ui_tab_grouping.R
- global.R
- lang/translation.json
- modules/select_group_name_switch.R
- modules/set_groupname_button.R
- modules/set_rename_group_button.R
- server.R
- ui.R
To get the latest functionalities to the text branch, so those can be used when checking the text
> add latest functionalities

- CITATION.cff
> Issue 282, added citation file

- funs/database_fun.R
- global.R
- scripts/container_data_prep.R
Also fixed an error in the KNMI download function (Change in API)
> Added new date range and data prep script

- Dockerfile
- global.R
#290, moved dataprep to global
> Dataprep stage moved to global, #290

- server.R
> bug solved in 359

- global.R
- modules/select_date_range.R
- server.R
Small change in layout date picker.
use option in the daterangepicker to adapt to the chosen language
> #348; Small change in layout date picker.

- global.R
- modules/communication_module.R
- server.R
> Issue338, set cutoff value

- lang/translation.json
- server.R
- ui.R
> Develop to 385, add newest 

- scripts/queue_manager.R
> reordering scheduler and fixed ndr_counter

- modules/get_data_button.R
- server.R
From choose tab, when use this data button is clicked, move directly to explore tab #412
> Isssue 412

- scripts/make_database.R
- scripts/queue_manager.R
This PR fixes the scheduler. I also added (changed) a script to create a database filled with data from example cities and Hollandse Luchten project.
> Issue 416, run schedule
